// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task11.Data;

#nullable disable

namespace Task11.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240528113530_update operation types")]
    partial class updateoperationtypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task11.Models.FinancialOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("OperationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OperationTypeId");

                    b.ToTable("FinancialOperations");
                });

            modelBuilder.Entity("Task11.Models.OperationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "from working",
                            IsIncome = true,
                            IsTaxable = true,
                            Name = "Salary"
                        },
                        new
                        {
                            Id = 2,
                            Description = "tips and comissions etc",
                            IsIncome = true,
                            IsTaxable = true,
                            Name = "Bonus"
                        },
                        new
                        {
                            Id = 3,
                            Description = "short-term jobs performing a single task on demand",
                            IsIncome = true,
                            IsTaxable = true,
                            Name = "Side hustle"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            IsIncome = true,
                            IsTaxable = true,
                            Name = "Rental"
                        },
                        new
                        {
                            Id = 5,
                            Description = "from nice investments",
                            IsIncome = true,
                            IsTaxable = true,
                            Name = "Royalties"
                        },
                        new
                        {
                            Id = 6,
                            Description = "from nice investments 2",
                            IsIncome = true,
                            IsTaxable = false,
                            Name = "dividends"
                        },
                        new
                        {
                            Id = 7,
                            Description = "",
                            IsIncome = true,
                            IsTaxable = true,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            IsIncome = false,
                            IsTaxable = false,
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 9,
                            Description = "",
                            IsIncome = false,
                            IsTaxable = false,
                            Name = "Housing"
                        },
                        new
                        {
                            Id = 10,
                            Description = "",
                            IsIncome = false,
                            IsTaxable = false,
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = 11,
                            Description = "",
                            IsIncome = false,
                            IsTaxable = false,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 12,
                            Description = "",
                            IsIncome = false,
                            IsTaxable = false,
                            Name = "Personal"
                        });
                });

            modelBuilder.Entity("Task11.Models.FinancialOperation", b =>
                {
                    b.HasOne("Task11.Models.OperationType", "OperationType")
                        .WithMany()
                        .HasForeignKey("OperationTypeId");

                    b.Navigation("OperationType");
                });
#pragma warning restore 612, 618
        }
    }
}
